2020-03-25 11:45:32,642 werkzeug     11364 INFO     122     * Restarting with stat
2020-03-25 11:45:33,898 werkzeug     13368 WARNING  122     * Debugger is active!
2020-03-25 11:45:33,904 werkzeug     13368 INFO     122     * Debugger PIN: 215-678-611
2020-03-25 11:45:33,921 werkzeug     13368 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-03-25 11:45:38,252 werkzeug     13368 INFO     122    10.255.175.48 - - [25/Mar/2020 11:45:38] "GET /test HTTP/1.1" 200 -
2020-04-10 11:15:15,261 werkzeug     11824 INFO     122     * Restarting with stat
2020-04-10 11:15:16,531 werkzeug     14516 WARNING  122     * Debugger is active!
2020-04-10 11:15:16,556 werkzeug     14516 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:15:16,596 werkzeug     14516 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:16:46,103 werkzeug     14516 INFO     122    10.255.175.48 - - [10/Apr/2020 11:16:46] "GET / HTTP/1.1" 404 -
2020-04-10 11:16:53,193 werkzeug     14516 INFO     122    10.255.175.48 - - [10/Apr/2020 11:16:53] "GET /test HTTP/1.1" 200 -
2020-04-10 11:17:12,761 werkzeug     14516 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\test.py', reloading
2020-04-10 11:17:12,845 werkzeug     11824 INFO     122     * Restarting with stat
2020-04-10 11:17:16,418 werkzeug     1048 WARNING  122     * Debugger is active!
2020-04-10 11:17:16,446 werkzeug     1048 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:17:16,508 werkzeug     1048 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:17:16,669 werkzeug     1048 INFO     122    10.255.175.48 - - [10/Apr/2020 11:17:16] "GET /test HTTP/1.1" 200 -
2020-04-10 11:21:05,175 werkzeug     1048 INFO     122    10.255.175.48 - - [10/Apr/2020 11:21:05] "GET /file/download HTTP/1.1" 404 -
2020-04-10 11:21:48,798 werkzeug     1048 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\app\\file\\file.py', reloading
2020-04-10 11:21:48,837 werkzeug     11824 INFO     122     * Restarting with stat
2020-04-10 11:21:50,229 werkzeug     2660 WARNING  122     * Debugger is active!
2020-04-10 11:21:50,235 werkzeug     2660 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:21:50,250 werkzeug     2660 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:23:09,903 werkzeug     2660 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\app\\file\\file.py', reloading
2020-04-10 11:23:09,965 werkzeug     11824 INFO     122     * Restarting with stat
2020-04-10 11:23:11,306 werkzeug     10148 WARNING  122     * Debugger is active!
2020-04-10 11:23:11,312 werkzeug     10148 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:23:11,328 werkzeug     10148 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:23:20,899 werkzeug     10148 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:23:20,937 werkzeug     11824 INFO     122     * Restarting with stat
2020-04-10 11:23:22,237 werkzeug     15188 WARNING  122     * Debugger is active!
2020-04-10 11:23:22,244 werkzeug     15188 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:23:22,261 werkzeug     15188 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:23:30,784 werkzeug     15188 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:23:30,831 werkzeug     11824 INFO     122     * Restarting with stat
2020-04-10 11:23:32,301 werkzeug     956 WARNING  122     * Debugger is active!
2020-04-10 11:23:32,308 werkzeug     956 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:23:32,323 werkzeug     956 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:25:13,682 werkzeug     956 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:25:13,723 werkzeug     11824 INFO     122     * Restarting with stat
2020-04-10 11:25:15,002 werkzeug     5252 WARNING  122     * Debugger is active!
2020-04-10 11:25:15,009 werkzeug     5252 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:25:15,024 werkzeug     5252 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:25:56,907 job          5252 ERROR    82     ==================  FileDownload  ==================
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 12, in process
    file_path = param['file_path'].rsplit("/", 1)
TypeError: 'NoneType' object is not subscriptable
2020-04-10 11:25:56,909 job          5252 ERROR    85     'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 12, in process
    file_path = param['file_path'].rsplit("/", 1)
TypeError: 'NoneType' object is not subscriptable
2020-04-10 11:25:56,910 werkzeug     5252 INFO     122    10.255.175.48 - - [10/Apr/2020 11:25:56] "GET /file/download?file_path=E:/me/Qinsy/flask_test/file&file_name=≤‚ ‘.txt HTTP/1.1" 200 -
2020-04-10 11:26:37,028 werkzeug     13892 INFO     122     * Restarting with stat
2020-04-10 11:26:38,343 werkzeug     1984 WARNING  122     * Debugger is active!
2020-04-10 11:26:38,349 werkzeug     1984 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:26:38,367 werkzeug     1984 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:26:49,095 job          1984 ERROR    82     ==================  FileDownload  ==================
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 13, in process
    response = make_response(send_from_directory(file_path[0], file_path[1]))
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\flask\helpers.py", line 767, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2020-04-10 11:26:49,120 job          1984 ERROR    85     404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 13, in process
    response = make_response(send_from_directory(file_path[0], file_path[1]))
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\flask\helpers.py", line 767, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2020-04-10 11:26:49,123 werkzeug     1984 INFO     122    10.255.175.48 - - [10/Apr/2020 11:26:49] "GET /file/download?file_path=E:/me/Qinsy/flask_test/file&file_name=≤‚ ‘.txt HTTP/1.1" 200 -
2020-04-10 11:27:17,477 werkzeug     1984 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:27:17,521 werkzeug     13892 INFO     122     * Restarting with stat
2020-04-10 11:28:59,345 werkzeug     14568 INFO     122     * Restarting with stat
2020-04-10 11:29:00,589 werkzeug     16312 WARNING  122     * Debugger is active!
2020-04-10 11:29:00,595 werkzeug     16312 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:29:00,612 werkzeug     16312 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:29:02,562 job          16312 ERROR    82     ==================  FileDownload  ==================
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 17, in process
    response = make_response(send_from_directory(file_path[0], file_path[1]))
IndexError: list index out of range
2020-04-10 11:29:02,564 job          16312 ERROR    85     list index out of range
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 17, in process
    response = make_response(send_from_directory(file_path[0], file_path[1]))
IndexError: list index out of range
2020-04-10 11:29:02,565 werkzeug     16312 INFO     122    10.255.175.48 - - [10/Apr/2020 11:29:02] "GET /file/download?file_path=E:/me/Qinsy/flask_test/file&file_name=≤‚ ‘.txt HTTP/1.1" 200 -
2020-04-10 11:30:00,983 job          16312 ERROR    82     ==================  FileDownload  ==================
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 17, in process
    response = make_response(send_from_directory(file_path[0], file_path[1]))
IndexError: list index out of range
2020-04-10 11:30:00,984 job          16312 ERROR    85     list index out of range
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 17, in process
    response = make_response(send_from_directory(file_path[0], file_path[1]))
IndexError: list index out of range
2020-04-10 11:30:00,987 werkzeug     16312 INFO     122    10.255.175.48 - - [10/Apr/2020 11:30:00] "GET /file/download?file_path=E:/me/Qinsy/flask_test/file&file_name=≤‚ ‘.txt HTTP/1.1" 200 -
2020-04-10 11:30:04,913 job          16312 ERROR    82     ==================  FileDownload  ==================
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 17, in process
    response = make_response(send_from_directory(file_path[0], file_path[1]))
IndexError: list index out of range
2020-04-10 11:30:04,914 job          16312 ERROR    85     list index out of range
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 17, in process
    response = make_response(send_from_directory(file_path[0], file_path[1]))
IndexError: list index out of range
2020-04-10 11:30:04,915 werkzeug     16312 INFO     122    10.255.175.48 - - [10/Apr/2020 11:30:04] "GET /file/download?file_path=E:/me/Qinsy/flask_test/file/œ¬‘ÿ≤‚ ‘Œƒº˛.txt&file_name=≤‚ ‘.txt HTTP/1.1" 200 -
2020-04-10 11:30:26,003 job          16312 ERROR    82     ==================  FileDownload  ==================
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 17, in process
    response = make_response(send_from_directory(file_path[0], file_path[1]))
IndexError: list index out of range
2020-04-10 11:30:26,003 job          16312 ERROR    85     list index out of range
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 17, in process
    response = make_response(send_from_directory(file_path[0], file_path[1]))
IndexError: list index out of range
2020-04-10 11:30:26,005 werkzeug     16312 INFO     122    10.255.175.48 - - [10/Apr/2020 11:30:26] "GET /file/download?file_path=E:/me/Qinsy/flask_test/file/œ¬‘ÿ≤‚ ‘Œƒº˛.txt&file_name=≤‚ ‘.txt HTTP/1.1" 200 -
2020-04-10 11:30:57,187 werkzeug     16312 INFO     122    10.255.175.48 - - [10/Apr/2020 11:30:57] "GET /file/download?file_path=E:%5Cme%5CQinsy%5Cflask_test%5Cfile%5Cœ¬‘ÿ≤‚ ‘Œƒº˛.txt&file_name=≤‚ ‘.txt HTTP/1.1" 200 -
2020-04-10 11:31:07,316 werkzeug     16312 INFO     122    10.255.175.48 - - [10/Apr/2020 11:31:07] "GET /file/download?file_path=E:%5Cme%5CQinsy%5Cflask_test%5Cfile%5Cœ¬‘ÿ≤‚ ‘Œƒº˛.txt&file_name=≤‚ ‘.txt HTTP/1.1" 200 -
2020-04-10 11:33:39,737 werkzeug     16312 INFO     122    10.255.175.48 - - [10/Apr/2020 11:33:39] "POST /xls/upload HTTP/1.1" 404 -
2020-04-10 11:34:23,563 werkzeug     16312 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\run.py', reloading
2020-04-10 11:34:23,619 werkzeug     14568 INFO     122     * Restarting with stat
2020-04-10 11:34:24,990 werkzeug     15456 WARNING  122     * Debugger is active!
2020-04-10 11:34:24,998 werkzeug     15456 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:34:25,014 werkzeug     15456 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:34:29,530 job          15456 ERROR    82     ==================  XlsUpload  ==================
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 22, in process
    file = kwargs['request'].files['file']
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\werkzeug\datastructures.py", line 443, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-04-10 11:34:29,554 job          15456 ERROR    85     400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 22, in process
    file = kwargs['request'].files['file']
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\werkzeug\datastructures.py", line 443, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-04-10 11:34:29,556 werkzeug     15456 INFO     122    10.255.175.48 - - [10/Apr/2020 11:34:29] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 11:34:41,840 job          15456 ERROR    82     ==================  XlsUpload  ==================
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 42, in process
    logger.debug('µ⁄' + str(i+1) + '––' + 'µ⁄' + str(j+1) + '¡–£∫' + table[j])
TypeError: 'Sheet' object is not subscriptable
2020-04-10 11:34:41,841 job          15456 ERROR    85     'Sheet' object is not subscriptable
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 42, in process
    logger.debug('µ⁄' + str(i+1) + '––' + 'µ⁄' + str(j+1) + '¡–£∫' + table[j])
TypeError: 'Sheet' object is not subscriptable
2020-04-10 11:34:41,843 werkzeug     15456 INFO     122    10.255.175.48 - - [10/Apr/2020 11:34:41] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 11:35:25,121 job          15456 ERROR    82     ==================  XlsUpload  ==================
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 42, in process
    logger.debug('µ⁄' + str(i+1) + '––' + 'µ⁄' + str(j+1) + '¡–£∫' + table[j])
TypeError: 'Sheet' object is not subscriptable
2020-04-10 11:35:25,122 job          15456 ERROR    85     'Sheet' object is not subscriptable
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 42, in process
    logger.debug('µ⁄' + str(i+1) + '––' + 'µ⁄' + str(j+1) + '¡–£∫' + table[j])
TypeError: 'Sheet' object is not subscriptable
2020-04-10 11:35:25,124 werkzeug     15456 INFO     122    10.255.175.48 - - [10/Apr/2020 11:35:25] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 11:35:41,024 werkzeug     15456 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\xls\\xls.py', reloading
2020-04-10 11:35:41,071 werkzeug     14568 INFO     122     * Restarting with stat
2020-04-10 11:35:42,432 werkzeug     5752 WARNING  122     * Debugger is active!
2020-04-10 11:35:42,438 werkzeug     5752 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:35:42,454 werkzeug     5752 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:35:48,724 job          5752 ERROR    82     ==================  XlsUpload  ==================
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 42, in process
    logger.debug('µ⁄' + str(i+1) + '––' + 'µ⁄' + str(j+1) + '¡–£∫' + info[j])
TypeError: can only concatenate str (not "float") to str
2020-04-10 11:35:48,725 job          5752 ERROR    85     can only concatenate str (not "float") to str
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 42, in process
    logger.debug('µ⁄' + str(i+1) + '––' + 'µ⁄' + str(j+1) + '¡–£∫' + info[j])
TypeError: can only concatenate str (not "float") to str
2020-04-10 11:35:48,726 werkzeug     5752 INFO     122    10.255.175.48 - - [10/Apr/2020 11:35:48] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 11:36:09,003 werkzeug     5752 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\xls\\xls.py', reloading
2020-04-10 11:36:09,049 werkzeug     14568 INFO     122     * Restarting with stat
2020-04-10 11:36:10,428 werkzeug     10216 WARNING  122     * Debugger is active!
2020-04-10 11:36:10,434 werkzeug     10216 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:36:10,450 werkzeug     10216 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:36:14,007 werkzeug     10216 INFO     122    10.255.175.48 - - [10/Apr/2020 11:36:14] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 11:36:34,867 werkzeug     10216 INFO     122    10.255.175.48 - - [10/Apr/2020 11:36:34] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 11:37:03,098 utils.pg_util 14732 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:37:03,319 utils.pg_util 14732 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:37:03,333 werkzeug     14732 INFO     122     * Restarting with stat
2020-04-10 11:37:04,424 utils.pg_util 11412 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:37:04,633 utils.pg_util 11412 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:37:04,642 werkzeug     11412 WARNING  122     * Debugger is active!
2020-04-10 11:37:04,648 werkzeug     11412 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:37:04,662 werkzeug     11412 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:37:06,669 job          11412 DEBUG    63     ==================  XlsUpload  ==================
2020-04-10 11:37:11,553 job.xls.xls  11412 DEBUG    42     µ⁄1––µ⁄1¡–£∫11.0
2020-04-10 11:37:11,553 job.xls.xls  11412 DEBUG    42     µ⁄1––µ⁄2¡–£∫12.0
2020-04-10 11:37:11,554 job.xls.xls  11412 DEBUG    42     µ⁄1––µ⁄3¡–£∫13.0
2020-04-10 11:37:11,554 job.xls.xls  11412 DEBUG    42     µ⁄1––µ⁄4¡–£∫14.0
2020-04-10 11:37:11,554 job.xls.xls  11412 DEBUG    42     µ⁄2––µ⁄1¡–£∫21.0
2020-04-10 11:37:11,555 job.xls.xls  11412 DEBUG    42     µ⁄2––µ⁄2¡–£∫22.0
2020-04-10 11:37:11,555 job.xls.xls  11412 DEBUG    42     µ⁄2––µ⁄3¡–£∫23.0
2020-04-10 11:37:11,555 job.xls.xls  11412 DEBUG    42     µ⁄2––µ⁄4¡–£∫24.0
2020-04-10 11:37:11,557 werkzeug     11412 INFO     122    10.255.175.48 - - [10/Apr/2020 11:37:11] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 11:37:47,696 job          11412 DEBUG    63     ==================  XlsExport  ==================
2020-04-10 11:37:47,729 werkzeug     11412 INFO     122    10.255.175.48 - - [10/Apr/2020 11:37:47] "POST /xls/export HTTP/1.1" 200 -
2020-04-10 11:38:25,421 werkzeug     11412 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\xls\\xls.py', reloading
2020-04-10 11:38:25,470 werkzeug     14732 INFO     122     * Restarting with stat
2020-04-10 11:38:26,596 utils.pg_util 15684 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:38:26,813 utils.pg_util 15684 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:38:26,823 werkzeug     15684 WARNING  122     * Debugger is active!
2020-04-10 11:38:26,829 werkzeug     15684 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:38:26,845 werkzeug     15684 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:38:55,485 werkzeug     15684 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\xls\\xls.py', reloading
2020-04-10 11:38:55,539 werkzeug     14732 INFO     122     * Restarting with stat
2020-04-10 11:38:56,672 utils.pg_util 11304 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:38:56,883 utils.pg_util 11304 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:38:56,891 werkzeug     11304 WARNING  122     * Debugger is active!
2020-04-10 11:38:56,897 werkzeug     11304 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:38:56,913 werkzeug     11304 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:39:22,434 werkzeug     11304 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\xls\\xls.py', reloading
2020-04-10 11:39:22,482 werkzeug     14732 INFO     122     * Restarting with stat
2020-04-10 11:39:23,709 utils.pg_util 1856 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:39:23,925 utils.pg_util 1856 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:39:23,933 werkzeug     1856 WARNING  122     * Debugger is active!
2020-04-10 11:39:23,941 werkzeug     1856 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:39:23,959 werkzeug     1856 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:39:58,009 werkzeug     1856 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\xls\\xls.py', reloading
2020-04-10 11:39:58,054 werkzeug     14732 INFO     122     * Restarting with stat
2020-04-10 11:39:59,152 utils.pg_util 3612 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:39:59,378 utils.pg_util 3612 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:39:59,386 werkzeug     3612 WARNING  122     * Debugger is active!
2020-04-10 11:39:59,393 werkzeug     3612 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:39:59,410 werkzeug     3612 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:40:26,985 werkzeug     3612 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:40:27,036 werkzeug     14732 INFO     122     * Restarting with stat
2020-04-10 11:40:28,127 utils.pg_util 16248 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:40:28,350 utils.pg_util 16248 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:40:28,363 werkzeug     16248 WARNING  122     * Debugger is active!
2020-04-10 11:40:28,372 werkzeug     16248 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:40:28,388 werkzeug     16248 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:40:33,053 job          16248 DEBUG    63     ==================  XlsExport  ==================
2020-04-10 11:40:33,060 werkzeug     16248 INFO     122    10.255.175.48 - - [10/Apr/2020 11:40:33] "POST /xls/export HTTP/1.1" 200 -
2020-04-10 11:41:15,232 werkzeug     16248 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\xls\\xls.py', reloading
2020-04-10 11:41:15,279 werkzeug     14732 INFO     122     * Restarting with stat
2020-04-10 11:41:16,515 utils.pg_util 10428 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:41:16,727 utils.pg_util 10428 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:41:16,735 werkzeug     10428 WARNING  122     * Debugger is active!
2020-04-10 11:41:16,741 werkzeug     10428 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:41:16,757 werkzeug     10428 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:41:20,027 werkzeug     10428 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\xls\\xls.py', reloading
2020-04-10 11:41:20,080 werkzeug     14732 INFO     122     * Restarting with stat
2020-04-10 11:41:21,196 utils.pg_util 14204 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:41:21,411 utils.pg_util 14204 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:41:21,419 werkzeug     14204 WARNING  122     * Debugger is active!
2020-04-10 11:41:21,426 werkzeug     14204 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:41:21,443 werkzeug     14204 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:41:24,646 werkzeug     14204 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\xls\\xls.py', reloading
2020-04-10 11:41:24,687 werkzeug     14732 INFO     122     * Restarting with stat
2020-04-10 11:41:25,774 utils.pg_util 14864 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:41:25,983 utils.pg_util 14864 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:41:25,991 werkzeug     14864 WARNING  122     * Debugger is active!
2020-04-10 11:41:25,997 werkzeug     14864 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:41:26,013 werkzeug     14864 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:41:29,343 utils.pg_util 13864 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:41:29,559 utils.pg_util 13864 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:41:29,574 werkzeug     13864 INFO     122     * Restarting with stat
2020-04-10 11:41:30,697 utils.pg_util 14316 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:41:30,933 utils.pg_util 14316 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:41:30,941 werkzeug     14316 WARNING  122     * Debugger is active!
2020-04-10 11:41:30,948 werkzeug     14316 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:41:30,964 werkzeug     14316 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:41:31,899 job          14316 DEBUG    63     ==================  XlsExport  ==================
2020-04-10 11:41:31,938 werkzeug     14316 INFO     122    10.255.175.48 - - [10/Apr/2020 11:41:31] "POST /xls/export HTTP/1.1" 200 -
2020-04-10 11:42:30,217 werkzeug     14316 INFO     122    10.255.175.48 - - [10/Apr/2020 11:42:30] "POST /file/download?file_path=E:%5Cme%5CQinsy%5Cflask_test%5Cfile%5Cxls%5C1586490091.9006011&file_name=≤‚ ‘.xls HTTP/1.1" 405 -
2020-04-10 11:42:39,762 job          14316 DEBUG    63     ==================  FileDownload  ==================
2020-04-10 11:42:39,765 werkzeug     14316 INFO     122    10.255.175.48 - - [10/Apr/2020 11:42:39] "GET /file/download?file_path=E:%5Cme%5CQinsy%5Cflask_test%5Cfile%5Cxls%5C1586490091.9006011&file_name=≤‚ ‘.xls HTTP/1.1" 200 -
2020-04-10 11:45:09,784 werkzeug     14316 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:45:09,833 werkzeug     13864 INFO     122     * Restarting with stat
2020-04-10 11:45:11,104 utils.pg_util 13328 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:45:11,312 utils.pg_util 13328 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:45:11,320 werkzeug     13328 WARNING  122     * Debugger is active!
2020-04-10 11:45:11,326 werkzeug     13328 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:45:11,342 werkzeug     13328 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:45:20,933 werkzeug     13328 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:45:20,978 werkzeug     13864 INFO     122     * Restarting with stat
2020-04-10 11:45:22,080 utils.pg_util 7376 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:45:22,292 utils.pg_util 7376 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:45:22,301 werkzeug     7376 WARNING  122     * Debugger is active!
2020-04-10 11:45:22,308 werkzeug     7376 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:45:22,324 werkzeug     7376 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:45:31,878 werkzeug     7376 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:45:31,923 werkzeug     13864 INFO     122     * Restarting with stat
2020-04-10 11:45:32,986 utils.pg_util 15408 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:45:33,201 utils.pg_util 15408 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:45:33,209 werkzeug     15408 WARNING  122     * Debugger is active!
2020-04-10 11:45:33,216 werkzeug     15408 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:45:33,231 werkzeug     15408 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:46:03,976 werkzeug     15408 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:46:04,019 werkzeug     13864 INFO     122     * Restarting with stat
2020-04-10 11:47:02,726 utils.pg_util 13216 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:47:02,948 utils.pg_util 13216 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:47:02,963 werkzeug     13216 INFO     122     * Restarting with stat
2020-04-10 11:47:04,037 utils.pg_util 2260 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:47:04,253 utils.pg_util 2260 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:47:04,261 werkzeug     2260 WARNING  122     * Debugger is active!
2020-04-10 11:47:04,268 werkzeug     2260 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:47:04,284 werkzeug     2260 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:47:29,081 job          2260 DEBUG    63     ==================  FileUpload  ==================
2020-04-10 11:47:29,083 job          2260 ERROR    85     'NoneType' object has no attribute 'seek'
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 39, in process
    f.seek(0)
AttributeError: 'NoneType' object has no attribute 'seek'
2020-04-10 11:47:29,085 werkzeug     2260 INFO     122    10.255.175.48 - - [10/Apr/2020 11:47:29] "POST /file/upload HTTP/1.1" 200 -
2020-04-10 11:47:47,748 werkzeug     2260 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:47:47,798 werkzeug     13216 INFO     122     * Restarting with stat
2020-04-10 11:47:48,864 utils.pg_util 9504 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:47:49,083 utils.pg_util 9504 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:47:49,091 werkzeug     9504 WARNING  122     * Debugger is active!
2020-04-10 11:47:49,098 werkzeug     9504 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:47:49,113 werkzeug     9504 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:47:57,624 werkzeug     9504 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:47:57,677 werkzeug     13216 INFO     122     * Restarting with stat
2020-04-10 11:47:58,780 utils.pg_util 11696 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:47:58,989 utils.pg_util 11696 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:47:58,997 werkzeug     11696 WARNING  122     * Debugger is active!
2020-04-10 11:47:59,004 werkzeug     11696 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:47:59,020 werkzeug     11696 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:48:06,492 werkzeug     11696 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:48:06,536 werkzeug     13216 INFO     122     * Restarting with stat
2020-04-10 11:48:07,667 utils.pg_util 232 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:48:07,882 utils.pg_util 232 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:48:07,891 werkzeug     232 WARNING  122     * Debugger is active!
2020-04-10 11:48:07,897 werkzeug     232 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:48:07,914 werkzeug     232 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:48:10,277 job          232 DEBUG    63     ==================  FileUpload  ==================
2020-04-10 11:48:10,284 job          232 ERROR    85     'NoneType' object has no attribute 'save'
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 38, in process
    f.save(save_path)
AttributeError: 'NoneType' object has no attribute 'save'
2020-04-10 11:48:10,286 werkzeug     232 INFO     122    10.255.175.48 - - [10/Apr/2020 11:48:10] "POST /file/upload HTTP/1.1" 200 -
2020-04-10 11:48:41,827 job          232 DEBUG    63     ==================  FileUpload  ==================
2020-04-10 11:48:45,327 job          232 ERROR    85     'NoneType' object has no attribute 'save'
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 38, in process
    f.save(save_path)
AttributeError: 'NoneType' object has no attribute 'save'
2020-04-10 11:48:45,329 werkzeug     232 INFO     122    10.255.175.48 - - [10/Apr/2020 11:48:45] "POST /file/upload HTTP/1.1" 200 -
2020-04-10 11:49:01,972 werkzeug     232 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:49:02,022 werkzeug     13216 INFO     122     * Restarting with stat
2020-04-10 11:49:03,119 utils.pg_util 15724 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:49:03,333 utils.pg_util 15724 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:49:03,340 werkzeug     15724 WARNING  122     * Debugger is active!
2020-04-10 11:49:03,347 werkzeug     15724 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:49:03,363 werkzeug     15724 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:49:21,190 utils.pg_util 13848 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:49:21,406 utils.pg_util 13848 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:49:21,420 werkzeug     13848 INFO     122     * Restarting with stat
2020-04-10 11:49:22,498 utils.pg_util 10812 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:49:22,717 utils.pg_util 10812 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:49:22,725 werkzeug     10812 WARNING  122     * Debugger is active!
2020-04-10 11:49:22,732 werkzeug     10812 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:49:22,748 werkzeug     10812 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:49:24,777 job          10812 DEBUG    63     ==================  FileUpload  ==================
2020-04-10 11:49:28,352 job          10812 ERROR    85     400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 36, in process
    f = kwargs['request'].files['file']
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\flask\debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\werkzeug\datastructures.py", line 443, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-04-10 11:49:28,388 werkzeug     10812 INFO     122    10.255.175.48 - - [10/Apr/2020 11:49:28] "POST /file/upload HTTP/1.1" 200 -
2020-04-10 11:49:52,673 job          10812 DEBUG    63     ==================  FileUpload  ==================
2020-04-10 11:49:56,352 job          10812 ERROR    85     400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 36, in process
    f = kwargs['request'].files['file']
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\flask\debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\werkzeug\datastructures.py", line 443, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-04-10 11:49:56,355 werkzeug     10812 INFO     122    10.255.175.48 - - [10/Apr/2020 11:49:56] "POST /file/upload HTTP/1.1" 200 -
2020-04-10 11:49:58,399 utils.pg_util 13820 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:49:58,616 utils.pg_util 13820 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:49:58,629 werkzeug     13820 INFO     122     * Restarting with stat
2020-04-10 11:49:59,723 utils.pg_util 9784 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:49:59,941 utils.pg_util 9784 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:49:59,949 werkzeug     9784 WARNING  122     * Debugger is active!
2020-04-10 11:49:59,956 werkzeug     9784 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:49:59,972 werkzeug     9784 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 11:50:04,333 job          9784 DEBUG    63     ==================  FileUpload  ==================
2020-04-10 11:50:08,220 job          9784 ERROR    85     400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\file\file.py", line 36, in process
    f = kwargs['request'].files['file']
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\flask\debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\werkzeug\datastructures.py", line 443, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-04-10 11:50:08,224 werkzeug     9784 INFO     122    10.255.175.48 - - [10/Apr/2020 11:50:08] "POST /file/upload HTTP/1.1" 200 -
2020-04-10 11:50:39,527 job          9784 DEBUG    63     ==================  XlsUpload  ==================
2020-04-10 11:50:39,528 job          9784 ERROR    85     400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 30, in process
    file = kwargs['request'].files['file']
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\flask\debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\werkzeug\datastructures.py", line 443, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-04-10 11:50:39,530 werkzeug     9784 INFO     122    10.255.175.48 - - [10/Apr/2020 11:50:39] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 11:50:50,668 job          9784 DEBUG    63     ==================  XlsUpload  ==================
2020-04-10 11:50:50,669 job          9784 ERROR    85     400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 30, in process
    file = kwargs['request'].files['file']
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\flask\debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\werkzeug\datastructures.py", line 443, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-04-10 11:50:50,670 werkzeug     9784 INFO     122    10.255.175.48 - - [10/Apr/2020 11:50:50] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 11:51:00,047 job          9784 DEBUG    63     ==================  XlsUpload  ==================
2020-04-10 11:51:04,606 job          9784 ERROR    85     400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 67, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 30, in process
    file = kwargs['request'].files['file']
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\flask\debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\werkzeug\datastructures.py", line 443, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-04-10 11:51:04,608 werkzeug     9784 INFO     122    10.255.175.48 - - [10/Apr/2020 11:51:04] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 11:51:30,224 job          9784 DEBUG    63     ==================  FileUpload  ==================
2020-04-10 11:51:38,034 werkzeug     9784 INFO     122    10.255.175.48 - - [10/Apr/2020 11:51:38] "POST /file/upload HTTP/1.1" 200 -
2020-04-10 11:52:35,019 job          9784 DEBUG    63     ==================  FileUpload  ==================
2020-04-10 11:52:39,013 werkzeug     9784 INFO     122    10.255.175.48 - - [10/Apr/2020 11:52:39] "POST /file/upload HTTP/1.1" 200 -
2020-04-10 11:56:49,941 werkzeug     9784 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\file\\file.py', reloading
2020-04-10 11:56:49,986 werkzeug     13820 INFO     122     * Restarting with stat
2020-04-10 11:56:51,054 utils.pg_util 9192 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 11:56:51,265 utils.pg_util 9192 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 11:56:51,272 werkzeug     9192 WARNING  122     * Debugger is active!
2020-04-10 11:56:51,278 werkzeug     9192 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 11:56:51,294 werkzeug     9192 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 12:02:46,604 utils.pg_util 12168 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:02:46,836 utils.pg_util 12168 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:02:46,853 werkzeug     12168 INFO     122     * Restarting with stat
2020-04-10 12:02:47,933 utils.pg_util 7256 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:02:48,144 utils.pg_util 7256 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:02:48,154 werkzeug     7256 WARNING  122     * Debugger is active!
2020-04-10 12:02:48,160 werkzeug     7256 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 12:02:48,176 werkzeug     7256 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 12:03:51,799 werkzeug     7256 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\app\\xls\\__init__.py', reloading
2020-04-10 12:03:51,877 werkzeug     12168 INFO     122     * Restarting with stat
2020-04-10 12:03:52,965 utils.pg_util 11268 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:03:53,192 utils.pg_util 11268 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:03:53,201 werkzeug     11268 WARNING  122     * Debugger is active!
2020-04-10 12:03:53,207 werkzeug     11268 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 12:03:53,222 werkzeug     11268 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 12:03:56,433 werkzeug     11268 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\app\\file\\__init__.py', reloading
2020-04-10 12:03:56,495 werkzeug     12168 INFO     122     * Restarting with stat
2020-04-10 12:03:57,577 utils.pg_util 15928 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:03:57,797 utils.pg_util 15928 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:03:57,809 werkzeug     15928 WARNING  122     * Debugger is active!
2020-04-10 12:03:57,817 werkzeug     15928 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 12:03:57,844 werkzeug     15928 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 12:05:11,967 werkzeug     15928 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\__init__.py', reloading
2020-04-10 12:05:12,031 werkzeug     12168 INFO     122     * Restarting with stat
2020-04-10 12:05:13,130 utils.pg_util 9588 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:05:13,355 utils.pg_util 9588 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:05:13,364 werkzeug     9588 WARNING  122     * Debugger is active!
2020-04-10 12:05:13,371 werkzeug     9588 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 12:05:13,392 werkzeug     9588 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 12:05:20,819 werkzeug     9588 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\__init__.py', reloading
2020-04-10 12:05:20,884 werkzeug     12168 INFO     122     * Restarting with stat
2020-04-10 12:05:22,058 utils.pg_util 15476 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:05:22,285 utils.pg_util 15476 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:05:22,294 werkzeug     15476 WARNING  122     * Debugger is active!
2020-04-10 12:05:22,300 werkzeug     15476 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 12:05:22,316 werkzeug     15476 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 12:05:23,410 werkzeug     15476 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\__init__.py', reloading
2020-04-10 12:05:23,480 werkzeug     12168 INFO     122     * Restarting with stat
2020-04-10 12:05:24,692 utils.pg_util 14316 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:05:24,918 utils.pg_util 14316 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:05:24,929 werkzeug     14316 WARNING  122     * Debugger is active!
2020-04-10 12:05:24,935 werkzeug     14316 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 12:05:24,952 werkzeug     14316 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 12:34:32,561 utils.pg_util 14628 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:34:32,806 utils.pg_util 14628 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:34:32,836 werkzeug     14628 INFO     122     * Restarting with stat
2020-04-10 12:34:33,978 utils.pg_util 12708 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:34:34,215 utils.pg_util 12708 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:34:34,225 werkzeug     12708 WARNING  122     * Debugger is active!
2020-04-10 12:34:34,254 werkzeug     12708 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 12:34:34,408 werkzeug     12708 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 12:34:40,369 job          12708 DEBUG    63     ==================  XlsUpload  ==================
2020-04-10 12:34:40,371 job          12708 ERROR    84     'FileStorage' object is not subscriptable
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 66, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 36, in process
    data = xlrd.open_workbook(file_contents=file)
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\xlrd\__init__.py", line 108, in open_workbook
    peek = file_contents[:peeksz]
TypeError: 'FileStorage' object is not subscriptable
2020-04-10 12:34:40,373 werkzeug     12708 INFO     122    10.255.175.48 - - [10/Apr/2020 12:34:40] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 12:34:49,049 job          12708 DEBUG    63     ==================  XlsUpload  ==================
2020-04-10 12:34:55,211 job          12708 ERROR    84     'FileStorage' object is not subscriptable
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 66, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 36, in process
    data = xlrd.open_workbook(file_contents=file)
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\xlrd\__init__.py", line 108, in open_workbook
    peek = file_contents[:peeksz]
TypeError: 'FileStorage' object is not subscriptable
2020-04-10 12:34:55,214 werkzeug     12708 INFO     122    10.255.175.48 - - [10/Apr/2020 12:34:55] "POST /xls/upload HTTP/1.1" 200 -
2020-04-10 12:35:36,328 werkzeug     12708 INFO     122     * Detected change in 'E:\\me\\Qinsy\\flask_test\\job\\xls\\xls.py', reloading
2020-04-10 12:35:36,417 werkzeug     14628 INFO     122     * Restarting with stat
2020-04-10 12:35:37,647 utils.pg_util 4772 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:35:37,868 utils.pg_util 4772 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:35:37,880 werkzeug     4772 WARNING  122     * Debugger is active!
2020-04-10 12:35:37,888 werkzeug     4772 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 12:35:37,906 werkzeug     4772 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 12:35:43,474 utils.pg_util 9420 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:35:43,693 utils.pg_util 9420 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:35:43,708 werkzeug     9420 INFO     122     * Restarting with stat
2020-04-10 12:35:44,864 utils.pg_util 6644 DEBUG    17     >>>>>>pg_pool start create>>>>>>
2020-04-10 12:35:45,114 utils.pg_util 6644 DEBUG    28     >>>>>>pg_pool create success>>>>>>
2020-04-10 12:35:45,124 werkzeug     6644 WARNING  122     * Debugger is active!
2020-04-10 12:35:45,132 werkzeug     6644 INFO     122     * Debugger PIN: 215-678-611
2020-04-10 12:35:45,154 werkzeug     6644 INFO     122     * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
2020-04-10 12:35:45,279 job          6644 DEBUG    63     ==================  XlsUpload  ==================
2020-04-10 12:35:45,281 job          6644 ERROR    84     Unsupported format, or corrupt file: Expected BOF record; found b'null'
Traceback (most recent call last):
  File "E:\me\Qinsy\flask_test\job\__init__.py", line 66, in do
    msg = self.process(**kwargs)
  File "E:\me\Qinsy\flask_test\job\xls\xls.py", line 36, in process
    data = xlrd.open_workbook(file_contents=file.read())
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\xlrd\__init__.py", line 157, in open_workbook
    ragged_rows=ragged_rows,
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\xlrd\book.py", line 92, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\xlrd\book.py", line 1278, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "E:\me\Qinsy\flask_test\venv\lib\site-packages\xlrd\book.py", line 1272, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'null'
2020-04-10 12:35:45,283 werkzeug     6644 INFO     122    10.255.175.48 - - [10/Apr/2020 12:35:45] "POST /xls/upload HTTP/1.1" 200 -
